### ISSUE TITLE
failed start bot

### ISSUE THREAD

**Issue by nenofetch** [ibnusyawall/aex-bot#13]
pas node . (starting bot) saya mengalami suatu masalah seperti berikut

![2020-10-21_16-24](https://user-images.githubusercontent.com/22952560/96700825-13163780-13ba-11eb-89be-86cfe8c0dfa1.png)

mohon bantuannya, terimakasih

**Comment by ibnusyawall** [comment]
silahkan diupdate kembali, sudah saya patch.

**Comment by nenofetch** [comment]
Pas npm start sekarang tidak memunculkan qr code nya mas, padahal saya sudah isi file .env nya
