### ISSUE TITLE
impostor 🐊

### ISSUE THREAD

**Issue by MFarelS** [ibnusyawall/aex-bot#25]
![IMG-20201127-WA0661](https://user-images.githubusercontent.com/58540890/100446691-d4268080-30e1-11eb-814e-c7b738aee684.jpg)
Hehe

**Comment by MFarelS** [comment]
![IMG-20201127-WA0712](https://user-images.githubusercontent.com/58540890/100455477-579b9e00-30f1-11eb-89d0-55051d220d5a.jpg)
Awokwaokwaokwaok

**Comment by MFarelS** [comment]
Source : Abang @dandyraka

**Comment by dandyraka** [comment]
> Source : Abang @dandyraka

Maksudnya?

**Comment by MFarelS** [comment]
> > Source : Abang @dandyraka
> 
> Maksudnya?

Kaga
