### ISSUE TITLE
tambahin fitur min

### ISSUE THREAD

**Issue by ilham1104** [ibnusyawall/aex-bot#8]
tambahin fitur sticker maker min

**Comment by fdciabdul** [comment]
> tambahin fitur sticker maker min

belum bisa ya 👍

**Comment by ilham1104** [comment]
> > tambahin fitur sticker maker min
> 
> belum bisa ya 👍

knpa belum bisa min

**Comment by OKKY-FIRMANSYAH-RAMADHAN** [comment]
> > > tambahin fitur sticker maker min
> > 
> > 
> > belum bisa ya 👍
> 
> knpa belum bisa min



> > > tambahin fitur sticker maker min
> > 
> > 
> > belum bisa ya 👍
> 
> knpa belum bisa min

Numpang jawab sih , soalnya dari librarynya belum ada bro

**Comment by ibnusyawall** [comment]
sudah saya update, include fitur-fitur (termasuk fitur stiker) terbaru bisa di cek di readme.md yah kak
